# Action Cable uses Redis to administer connections, channels,
# and sending/receiving messages over the WebSocket.
production: &production
  adapter: redis
  url: redis://redistogo:92627ef52683cc9a240a99fa20eab572@viperfish.redistogo.com:11395
  host: viperfish.redistogo.com
  port: 11395
  password: 92627ef52683cc9a240a99fa20eab572
  inline: true
  timeout: 1

development: &development
  adapter: redis
  url: redis://localhost:6379
  host: localhost
  port: 6379
  timeout: 1
  inline: true

test: *development
