# Action Cable uses Redis to administer connections, channels,
# and sending/receiving messages over the WebSocket.
production: &production
  url: redis://localhost:6379
  adapter: redis

development: &development
  url: redis://localhost:6379

test: *development
